// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package database

var TableNames = struct {
	ApplyToken                string
	BlogPost                  string
	CloudflareBrowserStats    string
	CloudflareCountryStats    string
	CloudflareStats           string
	CloudflareStatusCodeStats string
	Company                   string
	CompanyEvent              string
	DeveloperProfile          string
	DeveloperProfileEvent     string
	DeveloperProfileMessage   string
	EditToken                 string
	EmailNotification         string
	EmailSubscribers          string
	FXRate                    string
	Image                     string
	Job                       string
	JobEvent                  string
	Meta                      string
	PurchaseEvent             string
	RecruiterProfile          string
	SearchEvent               string
	SeoLandingPage            string
	SeoLocation               string
	SeoSalary                 string
	SeoSkill                  string
	Sitemap                   string
	UserSignOnToken           string
	Users                     string
}{
	ApplyToken:                "apply_token",
	BlogPost:                  "blog_post",
	CloudflareBrowserStats:    "cloudflare_browser_stats",
	CloudflareCountryStats:    "cloudflare_country_stats",
	CloudflareStats:           "cloudflare_stats",
	CloudflareStatusCodeStats: "cloudflare_status_code_stats",
	Company:                   "company",
	CompanyEvent:              "company_event",
	DeveloperProfile:          "developer_profile",
	DeveloperProfileEvent:     "developer_profile_event",
	DeveloperProfileMessage:   "developer_profile_message",
	EditToken:                 "edit_token",
	EmailNotification:         "email_notification",
	EmailSubscribers:          "email_subscribers",
	FXRate:                    "fx_rate",
	Image:                     "image",
	Job:                       "job",
	JobEvent:                  "job_event",
	Meta:                      "meta",
	PurchaseEvent:             "purchase_event",
	RecruiterProfile:          "recruiter_profile",
	SearchEvent:               "search_event",
	SeoLandingPage:            "seo_landing_page",
	SeoLocation:               "seo_location",
	SeoSalary:                 "seo_salary",
	SeoSkill:                  "seo_skill",
	Sitemap:                   "sitemap",
	UserSignOnToken:           "user_sign_on_token",
	Users:                     "users",
}
